Traceback (most recent call last):
  File "/Users/queqbr/PlantHelper/.venv/bin/uvicorn", line 7, in <module>
    sys.exit(main())
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 423, in main
    run(
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 593, in run
    server.run()
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in run
    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/_compat.py", line 53, in asyncio_run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 438, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/queqbr/PlantHelper/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/queqbr/PlantHelper/server.py", line 53
    async def discover_model(key: str) -> Optional[str]:
IndentationError: unexpected indent
